/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import inc.config;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dzakiya
 */
public class bpLogin extends javax.swing.JFrame {

    Connection conn;
    Statement st;
    ResultSet rs;
    public static int id;

    private void bpLogin() {

        try {
            String username = tfUname.getText();
            String password = tfPW.getText();
            String sql = "SELECT * FROM KASIR WHERE USERNAME='" + username + "' AND PASSWORD=MD5('" + password + "')";

            conn = config.Conn();
            st = conn.createStatement();
            rs = st.executeQuery(sql);

            if (rs.next()) {

                if (rs.getInt("status") == 1) {
                    id = rs.getInt("ID_KASIR");
                    String akses = rs.getString("akses");

                    if (akses.equals("admin")) {
                        bpAdmin a = new bpAdmin();
                        a.show();
                    } else if (akses.equals("kasir")) {
                        bpKasir k = new bpKasir();
                        k.show();

                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Yah Akun Terblokir :(");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Log In Gagal!");
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());

        }

    }

    public static int getID() {
        return id;
    }

    public bpLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        left = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        right = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        iconuser = new javax.swing.JLabel();
        iconpw = new javax.swing.JLabel();
        tfUname = new javax.swing.JTextField();
        tfPW = new javax.swing.JPasswordField();
        btnLogIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        left.setBackground(new java.awt.Color(48, 58, 82));

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/bpputih120.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BUKUPEDIA");

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(leftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addContainerGap())
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        right.setBackground(new java.awt.Color(204, 204, 204));
        right.setPreferredSize(new java.awt.Dimension(200, 0));

        login.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(48, 58, 82));
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("Log In");

        iconuser.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        iconuser.setForeground(new java.awt.Color(48, 58, 82));
        iconuser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        iconuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icons8_user_40px_1.png"))); // NOI18N

        iconpw.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        iconpw.setForeground(new java.awt.Color(48, 58, 82));
        iconpw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icons8_lock_40px_1.png"))); // NOI18N

        tfUname.setBackground(new java.awt.Color(204, 204, 204));
        tfUname.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        tfUname.setForeground(new java.awt.Color(48, 58, 82));
        tfUname.setText("Username");
        tfUname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));
        tfUname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfUnameMouseClicked(evt);
            }
        });
        tfUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnameActionPerformed(evt);
            }
        });

        tfPW.setBackground(new java.awt.Color(204, 204, 204));
        tfPW.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        tfPW.setForeground(new java.awt.Color(48, 58, 82));
        tfPW.setText("Password");
        tfPW.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 58, 82)));
        tfPW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfPWMouseClicked(evt);
            }
        });
        tfPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPWActionPerformed(evt);
            }
        });

        btnLogIn.setBackground(new java.awt.Color(48, 58, 82));
        btnLogIn.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        btnLogIn.setText("Log In");
        btnLogIn.setBorder(null);
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightLayout = new javax.swing.GroupLayout(right);
        right.setLayout(rightLayout);
        rightLayout.setHorizontalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(rightLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rightLayout.createSequentialGroup()
                        .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconuser)
                            .addComponent(iconpw))
                        .addGap(30, 30, 30)
                        .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPW, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 70, Short.MAX_VALUE))
        );
        rightLayout.setVerticalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(login)
                .addGap(33, 33, 33)
                .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfUname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconuser))
                .addGap(39, 39, 39)
                .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPW, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconpw))
                .addGap(18, 18, 18)
                .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(right, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(right, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnameActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // TODO add your handling code here:
        bpLogin();
        setVisible(false); //you can't see me!
        dispose();
    }//GEN-LAST:event_btnLogInActionPerformed

    private void tfPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPWActionPerformed

    private void tfUnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfUnameMouseClicked
        // TODO add your handling code here:
        tfUname.setText("");
    }//GEN-LAST:event_tfUnameMouseClicked

    private void tfPWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPWMouseClicked
        // TODO add your handling code here:
        tfPW.setText("");
    }//GEN-LAST:event_tfPWMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bpLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bpLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bpLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bpLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bpLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel iconpw;
    private javax.swing.JLabel iconuser;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel left;
    private javax.swing.JLabel login;
    private javax.swing.JPanel right;
    private javax.swing.JPasswordField tfPW;
    private javax.swing.JTextField tfUname;
    // End of variables declaration//GEN-END:variables
}
